---
# 2021 hostname edict distro,distroversion,site,purpose,number
# (u-buntu/c-entos/rh-el/rk-rocky/a-arch/m-manjaro/d-ebian)

all:
  vars:
    jumpcloud_managed: false
    jumpcloudkey: "***REMOVED***"
    zerotier_managed: false
    zerotiernetwork: ***REMOVED***
  children:
    servers:
      vars:
        nfs_role: true
        nfs_mounts:
***REMOVED***
      hosts:
***REMOVED***
***REMOVED***
          amp_role: true
***REMOVED***
***REMOVED***
          awx_build_documentation: true
          awx_role: true
***REMOVED***
***REMOVED***
          nfs_role: true
          kubernetes_role: false
          jumpcloud_managed: false
          firewalld_role: true
          firewalld_ssh_managed: ztmanagement
          firewalld_custom_zones:
            - name: ztmanagement
              zone_short: "ZeroTier Management Network"
***REMOVED***
              zone_source_address:
***REMOVED***
                - "192.168.196.0/24"
              zone_services:
                - name: ftp
                  log: true
                  audit: true
                  log_prefix: "ftplogging"
                  action: drop
                - name: http
                  log: true
***REMOVED***
***REMOVED***
          nfs_role: true
          kubernetes_role: false
          jumpcloud_managed: false
          firewalld_role: true
          firewalld_ssh_managed: ztmanagement
          firewalld_custom_zones:
            - name: ztmanagement
              zone_short: "ZeroTier Management Network"
***REMOVED***
              zone_source_address:
***REMOVED***
                - "192.168.196.0/24"
              zone_services:
                - name: ftp
                  log: true
                  audit: true
                  log_prefix: "ftplogging"
                  action: drop
                - name: http
                  log: true
***REMOVED***
***REMOVED***
          nfs_role: false
          jumpcloud_managed: true
          zerotier_managed: true
***REMOVED***
***REMOVED***
          docker_role: true
***REMOVED***
***REMOVED***
          docker_role: true
          zerotier_managed: true
***REMOVED***
***REMOVED***
          cobbler_role: true
          cobbler_web: true
          firewalld_role: true
          firewalld_custom_zones:
***REMOVED***
***REMOVED***
***REMOVED***
              zone_source_address:
***REMOVED***
              zone_services:
                - name: tftp
                  action: accept
                - name: http
                  action: accept
                - name: https
                  action: accept
          nfs_mounts:
***REMOVED***
***REMOVED***
***REMOVED***
          docker_role: true
          zerotier_managed: true
          jumpcloud_managed: true
***REMOVED***
***REMOVED***
          nfs_role: false
          zerotier_managed: true
          jumpcloud_managed: true
          firewalld_role: true
    lindeal:
      vars:
        nfs_role: false
        jumpcloud_managed: true
        zerotier_managed: true
        fairgame_role: true
        fairgame_asin1: B08J5F3G18
        fairgame_asin1_min: 1800
        fairgame_asin1_max: 1950
      hosts:
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    kubernetes:
      vars:
        kubernetes_calico_subnet: 172.16.0.0/16
        kubernetes_control_plane_endpoint: 192.168.52.1
        kubernetes_hybrid_control_plane: true
        jumpcloud_managed: false
        zerotier_managed: false
        kubernetes_role: true
***REMOVED***
        nfs_role: true
        nfs_mounts:
***REMOVED***
        seriality: 1
      children:
        k1controllers:
          children:
            primaryctl:
              vars:
                kubernetes_primaryctl: true
              hosts:
***REMOVED***
***REMOVED***
            secondaryctl:
              hosts:
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
          vars:
            kubernetes_nodetype: controlplane
        k1nodes:
          children:
            workers:
              hosts:
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
          vars:
            kubernetes_nodetype: worker
    workstations:
      vars:
      hosts:
***REMOVED***
***REMOVED***
          nfs_role: true
          nfs_mounts:
***REMOVED***

