---
# 2021 hostname edict distro,distroversion,site,purpose,number
# (u-buntu/c-entos/rh-el/rk-rocky/a-arch/m-manjaro/d-ebian)

all:
  vars:
    jumpcloud_managed: false
    jumpcloudkey: "7366de64036dc8493a86cc12cf41950e1b6c1e1f"
    zerotier_managed: false
    zerotiernetwork: 8bd5124fd6fc5db6
  children:
    servers:
      vars:
        nfs_role: true
        nfs_mounts:
          - {source: "bigdaddy.endormoon.com", remotemountpoint: "/mnt/Rotational/NFSShare", localmountpoint: "/mnt/nfsshare"}
      hosts:
        amp.endormoon.com:
          ansible_host: 192.168.42.148
          amp_role: true
        awx.endormoon.com:
          ansible_host: 192.168.42.127
          awx_build_documentation: true
          awx_role: true
        basic.endormoon.com:
          ansible_host: 192.168.42.86
          nfs_role: true
          kubernetes_role: false
          jumpcloud_managed: false
          firewalld_role: true
          firewalld_ssh_managed: ztmanagement
          firewalld_custom_zones:
            - name: ztmanagement
              zone_short: "ZeroTier Management Network"
              zone_description: "Endormoon Zerotier Network for Node Management"
              zone_source_address:
                - "192.168.42.0/24"
                - "192.168.196.0/24"
              zone_services:
                - name: ftp
                  log: true
                  audit: true
                  log_prefix: "ftplogging"
                  action: drop
                - name: http
                  log: true
        centos.endormoon.com:
          ansible_host: 192.168.42.147
          nfs_role: true
          kubernetes_role: false
          jumpcloud_managed: false
          firewalld_role: true
          firewalld_ssh_managed: ztmanagement
          firewalld_custom_zones:
            - name: ztmanagement
              zone_short: "ZeroTier Management Network"
              zone_description: "Endormoon Zerotier Network for Node Management"
              zone_source_address:
                - "192.168.42.0/24"
                - "192.168.196.0/24"
              zone_services:
                - name: ftp
                  log: true
                  audit: true
                  log_prefix: "ftplogging"
                  action: drop
                - name: http
                  log: true
        deal.endormoon.com:
          ansible_host: 155.138.165.79
          nfs_role: false
          jumpcloud_managed: true
          zerotier_managed: true
        storj1.endormoon.com:
          ansible_host: 192.168.42.120
          docker_role: true
        sso.endormoon.com:
          ansible_host: 192.168.42.54
          docker_role: true
          zerotier_managed: true
        cobbler.endormoon.com:
          ansible_host: 192.168.42.134
          cobbler_role: true
          cobbler_web: true
          firewalld_role: true
          firewalld_custom_zones:
            - name: endormoon
              zone_short: "endormoonall"
              zone_description: "Endormoon Internal IPs"
              zone_source_address:
                - "192.168.42.0/24"
              zone_services:
                - name: tftp
                  action: accept
                - name: http
                  action: accept
                - name: https
                  action: accept
          nfs_mounts:
          - {source: "bigdaddy.lan.endormoon.com", remotemountpoint: "/mnt/Rotational/cobbler", localmountpoint: "/mnt/cobbler"}
        luvox.endormoon.com:
          ansible_host: 192.168.42.82
          docker_role: true
          zerotier_managed: true
          jumpcloud_managed: true
        webhost.server.endormoon.com:
          ansible_host: 192.168.52.64
          nfs_role: false
          zerotier_managed: true
          jumpcloud_managed: true
          firewalld_role: true
    lindeal:
      vars:
        nfs_role: false
        jumpcloud_managed: true
        zerotier_managed: true
        fairgame_role: true
        fairgame_asin1: B08J5F3G18
        fairgame_asin1_min: 1800
        fairgame_asin1_max: 1950
      hosts:
        lindeal1.endormoon.com:
          ansible_host: 139.177.203.42
        lindeal2.endormoon.com:
          ansible_host: 192.46.217.226
        lindeal3.endormoon.com:
          ansible_host: 45.79.89.83
        lindeal4.endormoon.com:
          ansible_host: 192.155.91.35
        dealbuster.endormoon.com:
          ansible_host: 194.195.211.233
    kubernetes:
      vars:
        kubernetes_calico_subnet: 172.16.0.0/16
        kubernetes_control_plane_endpoint: 192.168.52.1
        kubernetes_hybrid_control_plane: true
        jumpcloud_managed: false
        zerotier_managed: false
        kubernetes_role: true
        kubernetes_clusterworkdir: "/mnt/k8s/endortest"
        nfs_role: true
        nfs_mounts:
          - {source: "bigdaddy.lan.endormoon.com", remotemountpoint: "/mnt/Rotational/k8s", localmountpoint: "/mnt/k8s"}
        seriality: 1
      children:
        k1controllers:
          children:
            primaryctl:
              vars:
                kubernetes_primaryctl: true
              hosts:
                u20-kcp-01.server.endormoon.com:
                  ansible_host: 192.168.52.51
            secondaryctl:
              hosts:
                u20-kcp-02.server.endormoon.com:
                  ansible_host: 192.168.52.52
                #u20-kcp-03.server.endormoon.com:
                #  ansible_host: 192.168.52.53
                u20-kcp-04.server.endormoon.com:
                  ansible_host: 192.168.52.62
          vars:
            kubernetes_nodetype: controlplane
        k1nodes:
          children:
            workers:
              hosts:
                u20-kw-01.server.endormoon.com:
                  ansible_host: 192.168.52.55
                u20-kw-02.server.endormoon.com:
                  ansible_host: 192.168.52.56
                #u20-kw-03.server.endormoon.com:
                #  ansible_host: 192.168.52.57
                u20-kw-04.server.endormoon.com:
                  ansible_host: 192.168.52.60
          vars:
            kubernetes_nodetype: worker
    workstations:
      vars:
      hosts:
        remoet.endormoon.com:
          ansible_host: 192.168.42.142
          nfs_role: true
          nfs_mounts:
            - { source: "bigdaddy.endormoon.com", remotemountpoint: "/mnt/Rotational/BigDaddy", localmountpoint: "/mnt/bigdaddy" }

