---
# 2021 hostname edict distro,distroversion,site,purpose,number
# (u-buntu/c-entos/rh-el/rk-rocky/a-arch/m-manjaro/d-ebian)

all:
  vars:
  children:
    standalone-caches:
      vars:
      hosts:
        themachine:
# TODO: Configure Initial standalone interface. This is the staging IP. End config 
***REMOVED***
          nfs_role: false
          kubernetes_role: false
          jumpcloud_managed: false
          docker_role: false
          kvm_managed: true
