---
# tasks file for debian updates - endormoon base

- name: update all the packages
  apt:
    upgrade: dist
  become: true
  register: result
  until: result is not failed
  retries: 40
  delay: 20
  tags: update
