apiVersion: v1
kind: Namespace
metadata:
  name: lancache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lancache-rotational
spec:
  capacity:
    storage: 4500Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /rotational
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lancache-cache
  namespace: lancache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4500Gi
  volumeName: lancache-rotational
