apiVersion: v1
kind: Namespace
metadata:
  name: network
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pihole
spec:
  capacity:
    storage: 20M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /etc-pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole
  namespace: network
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20M
  volumeName: etc-pihole
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-dnsmasq-d
spec:
  capacity:
    storage: 20M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /etc-dnsmasq-d
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-dnsmasq-d
  namespace: network
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20M
  volumeName: etc-dnsmasq-d